version: '3.3'
services:
  prometheus:
    build: Prometheus
    image: 192.168.1.173:5000/prometheus
    ports:
      - "9090:9090"
    networks:
      - prometheus_nw
    hostname: prometheus
    volumes:
      - /data/prometheus:/prometheus
    deploy:
      placement:
        constraints: [node.role == manager]

  portainer:
    image: portainer/portainer
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/portainer:/data
    deploy:
      placement:
        constraints: [node.role == manager]

  nodeexporter:
    build: NodeExporter
    image: 192.168.1.173:5000/nodeexporter
    networks:
      - prometheus_nw
    deploy:
      mode: global
      # TODO OMG WTF This took all day
      # Need to write up an explanation
      # See also config in prometheus.yml
      endpoint_mode: dnsrr

  thedailywhiskers:
    build: TheDailyWhiskers
    image: 192.168.1.173:5000/thedailywhiskers
    networks:
      - prometheus_nw
    hostname: thedailywhiskers

  tinyserver:
    build: TinyServer
    image: 192.168.1.173:5000/tinyserver
    ports:
      - "80:80"

networks:
  prometheus_nw:
    # driver: overlay
    external: true
