version: '3.3'
services:

  # Services on the manager
  #
  prometheus:
    build: Prometheus
    image: 192.168.1.173:5000/prometheus
    ports:
      - "9090:9090"
    networks:
      - prometheus_nw
    hostname: prometheus
    volumes:
      - /data/prometheus:/prometheus
    deploy:
      placement:
        constraints: [node.role == manager]

  portainer:
    image: portainer/portainer
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/portainer:/data
    deploy:
      placement:
        constraints: [node.role == manager]

  # Global services
  #
  nodeexporter:
    build: NodeExporter
    image: 192.168.1.173:5000/nodeexporter
    networks:
      - prometheus_nw
    deploy:
      mode: global
      endpoint_mode: dnsrr

  # Services on workers
  #
  thedailywhiskers:
    build: TheDailyWhiskers
    image: 192.168.1.173:5000/thedailywhiskers
    networks:
      - prometheus_nw
    hostname: thedailywhiskers
    deploy:
      placement:
        constraints: [node.role != manager]

  tinyserver:
    build: TinyServer
    image: 192.168.1.173:5000/tinyserver
    ports:
      - "80:80"
    deploy:
      placement:
        constraints: [node.role != manager]

networks:
  prometheus_nw:
    driver: overlay
