version: '3'
services:
  thedailywhiskers:
    build: TheDailyWhiskers
    networks:
      - prometheus_nw
    hostname: thedailywhiskers

  prometheus:
    build: Prometheus
    ports:
      - "9090:9090"
    networks:
      - prometheus_nw
    hostname: prometheus
    volumes:
      - /data/prometheus:/prometheus

  portainer:
    image: portainer/portainer
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/portainer:/data

networks:
  prometheus_nw:
    driver: bridge
