global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'thedailywhiskers'
    static_configs:
      - targets: ['thedailywhiskers:8000']

  - job_name: 'nodeexporter'
    static_configs:
      - targets:
        - 'gandalf:9100'
        - 'frodo:9100'
        - 'boromir:9100'
        - 'faramir:9100'

rule_files:
  - alert.rules
