global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'cluster'
    static_configs:
      - targets: ['node_exporter:9100', 'localhost:9090', 'thedailywhiskers:8000']

rule_files:
  - alert.rules
